apiVersion: v1
kind: Service
metadata:
  name: kuvasz-service
  namespace: kuvasz
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: kuvasz-service
  type: LoadBalancer
