---
datasources:
  default:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    schema: 'public'
    username: 'postgres'
    password: 'pass'
---
basic-auth-config:
  user: user
  password: pass
