---
micronaut:
  security:
    basic-auth:
      user: dev
      password: pass
---
datasources:
  default:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'pass'
